apiVersion: v1
kind: Service
metadata:
  name: blue
spec:
  selector:
    domain: dev
    color: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
# test service with color blue for 01-blue-deployment.yaml that will map to this service now we take same configuration for green with preview service once deployment and preview services up test it once it success then change pointing of main service from blue to green and run 02-main-service.yaml again then services will point to green later we can drain the blue setup